from enum import Enum


class IssueType(Enum):
    PAYMENT_RELATED = "PAYMENT_RELATED"
    MUTUAL_FUND_RELATED = "MUTUAL_FUND_RELATED"
    GOLD_RELATED = "GOLD_RELATED"
    INSURANCE_RELATED = "INSURANCE_RELATED"
